# travis build script
language: python
python:
    - "2.7"


# dependencies
install:
    - cd ..

      # renpy
    - wget https://www.renpy.org/dl/7.1.1/renpy-7.1.1-sdk.tar.bz2
    - tar xf renpy-7.1.1-sdk.tar.bz2
    - rm renpy-7.1.1-sdk.tar.bz2
    - mv renpy-7.1.1-sdk renpy

      # mas build
    - wget https://s3-us-west-2.amazonaws.com/monika-after-story/ddlc/mas.zip
    - mkdir mas0105
    - unzip mas.zip -d mas0105

    # copy over files from game/
    - cp -Rf MonikaModDev/Monika\ After\ Story/* mas0105/

# environment to handle alsa issues
env:
    - SDL_AUDIODRIVER=dummy

# command to check syntax
script: 
    - python MonikaModDev/tools/travis.py
    - cd renpy && ./renpy.sh "../mas0105/" lint && ./renpy.sh launcher distribute "../mas0105/"
